CREATE TABLE tbProduto (
	codigo BIGINT (20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR (50) NOT NULL,
	tipo VARCHAR (50) NOT NULL,
	qtdeEstoque INT NOT NULL,
	valor DECIMAL (10, 2) NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;